# Generated by Django 4.2.1 on 2023-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
