# Generated by Django 4.2.1 on 2023-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_articles_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('paragraph', models.TextField()),
                ('logo', models.ImageField(unique=True, upload_to='')),
            ],
        ),
    ]
