# Generated by Django 4.2.1 on 2023-06-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_usersemails_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersemails',
            name='confirmation_code',
            field=models.URLField(blank=True, max_length=100, unique=True),
        ),
    ]
