# Generated by Django 4.2.1 on 2023-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_usersemails_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersemails',
            name='expiration_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
