# Generated by Django 4.2.1 on 2023-06-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_alter_usersemails_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersemails',
            old_name='valid',
            new_name='is_valid',
        ),
    ]
