# Generated by Django 4.2.1 on 2023-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_rename_valid_usersemails_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersemails',
            name='confirmation_delete',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersemails',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
