# Generated by Django 4.2.1 on 2023-06-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_usersemails_confirmation_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersemails',
            name='confirmation_delete',
        ),
    ]
