# Generated by Django 4.2.1 on 2023-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_remove_usersemails_confirmation_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersemails',
            name='confirmation_delete',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
