# Generated by Django 4.2.1 on 2023-07-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_remove_contactshistory_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactshistory',
            old_name='text',
            new_name='message',
        ),
    ]
