# Generated by Django 4.2.1 on 2023-07-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_rename_text_contactshistory_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersemails',
            old_name='expiration_time',
            new_name='confirm_expiration',
        ),
        migrations.AddField(
            model_name='usersemails',
            name='delete_expiration',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
