# Generated by Django 4.2.1 on 2023-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
