# Generated by Django 4.2.1 on 2023-05-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_articles_likes_articles_views_alter_articles_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
