# Generated by Django 4.2.1 on 2023-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(default='build-a-strong-mindset', max_length=200),
        ),
    ]
