# Generated by Django 4.2.1 on 2023-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_usersemails_confirmation_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersemails',
            name='confirmation_delete',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
