# Generated by Django 4.2.1 on 2023-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_usersemails_confirmation_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=5000)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
