# Generated by Django 4.2.1 on 2023-07-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_contactshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactshistory',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='contactshistory',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
